# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('publisher', models.CharField(max_length=32)),
            ],
        ),
    ]
